### PR TITLE
Code review-Microverse-project 2

### PR DESCRIPTION
**Pull request by Mandeln**
Good evening/morning ladies and gentlemen.

We created a branch for developing our second-week project (cloning the "Next Web" webpage) called "working".

We used solely HTML and CSS code.

We learned a lot about media queries and webpage adaptability.

In hopes of finalizing the project by Friday, we kindly ask for a code review.

Many thanks in advance,
Matija Maksimovic and Mark Allen

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @Mandeln and @CacheMeGifYouCan . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Feature branch should have a meaningful and descriptive name. Example: `the-next-web-clone`, `responsive-html-design`. Please edit the branch name, and update the PR branch IMPORTANT: **DO NOT** close and open a new PR, all can ben done in the same pull request. **DO NOT** close this PR, as it will contain the history of the reviews the project will get.
- [ ] Project is not passing all linters check
- [ ] The project should have a descriptive README.[ LINK](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- [ ] The project should have a live preview link, to generate one you could use [LINK](rawcdn.githack.com)
- [ ] The website doesn't look like the original design. Please use the browser media query inspector to check how all the sections of the website changes on different screen sizes, Desktop, Tablet, and Mobile.
  - [ ] Comparasion on desktop view
image
  - [ ] Comparasion on Tablet view
image
  - [ ] Comparasion on Mobile view
image
  - [ ] Sections to check responsiveness:
    - [ ] Navbar
    - [ ] Three image hero section
    - [ ] Latest news
    - [ ] Funding
    - [ ] Other cathegories
    - [ ] Latest Deals
    - [ ] Footer

- [ ] The website is not fully responsive
- [ ] The TNW logo in the footer is not displaying.
- [ ] Use full paths when calling files in the INDEX HTML file pretending each URL with `./` dot and slash, this applies also for other assets like images. Not using full paths could cause that some elements like images and stylesheets don't render properly or are not taken into consideration making the website not look as expected. example
```html
<!--BAD-->
<link rel="stylesheet" href="css/style.css" />

<!--GOOD-->
<link rel="stylesheet" href="./css/style.css" />
```
- [ ] Remove unnecessary files like `.DS_store`, and `notes.md`, .DS_store is duplicated, the second file is inside the css directory.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by MarcusAl** [comment]
Fixed ReadMe Section

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Mandeln and @CacheMeGifYouCan 
Good job with the changes! :tada: We are almost there :+1: .
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes 👇.
- [ ] This branch has conflicts please resolve them.
- [ ] 
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Mandeln** [comment]
Mr. Umair... please help us understand how to fix it

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job @team, thanks for making the required changes.

now you can merge, your project is approved :checkered_flag: 

- [ ] your project is approved but there is one last thing I want you to do, give a max-width value to all the sections starting from the latest news section cause on wide screens it's not displayed correctly.
image

## Happy Coding :tophat: 
_Zakariae El Mejdki_

**Pull request merged**
